import Foundation

/// S1 AI Push Guard：纯启发式判断一个 commit 看起来是不是 AI agent（Cursor /
/// Claude Code / Cline / Aider 等）写的。
///
/// 设计原则：
///   - **Indicative not authoritative**：UI 显示"看起来像"，给用户判断空间
///   - **保守**：宁可漏标，不要错标（一个普通 refactor 改 30 文件不该被标 AI）
///   - **多信号叠加**：单个信号不够，至少 2 个信号才算 likelyAI
///   - **纯函数**：无副作用，方便测试
enum AICommitDetector {

    /// 启发式判断单个 commit。
    /// - Parameters:
    ///   - author: commit author 字符串（可能是 name 或 email）
    ///   - authorEmail: %ae 拿到的 email（更可靠）
    ///   - subject: commit message 第一行
    ///   - changedFileCount: 这个 commit 改了几个文件（0 时跳过这个信号）
    static func detect(
        author: String,
        authorEmail: String?,
        subject: String,
        changedFileCount: Int = 0
    ) -> AILikelihood {
        var signals = 0

        // 信号 1: author email 匹配已知 AI agent pattern
        let emailLower = (authorEmail ?? "").lowercased()
        let authorLower = author.lowercased()
        let aiEmailPatterns = [
            "noreply@anthropic.com",
            "claude@anthropic.com",
            "cursor@cursor",
            "noreply@cursor.so",
            "agent@",
            "@bot.",
            "[bot]",
        ]
        if aiEmailPatterns.contains(where: emailLower.contains) ||
           aiEmailPatterns.contains(where: authorLower.contains) {
            signals += 1
        }

        // 信号 2: commit message 含 AI 协作标记
        let subjectLower = subject.lowercased()
        let aiMessageMarkers = [
            "co-authored-by: claude",
            "co-authored-by: cursor",
            "co-authored-by: github copilot",
            "🤖 generated",
            "generated with claude",
            "generated by cursor",
        ]
        if aiMessageMarkers.contains(where: subjectLower.contains) {
            signals += 1
        }

        // 信号 3: 一次改 ≥15 文件（人类常 ≤5；AI agent 经常一次 refactor 大片）
        if changedFileCount >= 15 {
            signals += 1
        }

        // 信号 4: subject 是 generic 占位词
        let trimmedSubject = subjectLower.trimmingCharacters(in: .whitespacesAndNewlines)
        let genericSubjects: Set<String> = [
            "updated files",
            "fix bug",
            "fix bugs",
            "update code",
            "update",
            "updates",
            "wip",
            "stuff",
            "changes",
            "misc",
            "fixes",
        ]
        if genericSubjects.contains(trimmedSubject) {
            signals += 1
        }

        switch signals {
        case 0:  return .unknown
        case 1:  return .maybeAI
        default: return .likelyAI
        }
    }
}
