import Foundation

/// S1 AI Push Guard：纯启发式判断一个 commit 看起来是不是 AI agent（Cursor /
/// Claude Code / Cline / Aider / Codex 等）写的。
///
/// 设计原则：
///   - **Indicative not authoritative**：UI 显示"看起来像"，给用户判断空间
///   - **保守**：宁可漏标，不要错标（一个普通 refactor 改 30 文件不该被标 AI）
///   - **强弱信号分级**：明确 attribution（trailer 里的 Co-Authored-By Claude）
///     就是强信号 —— 一条够 likelyAI；启发式信号（generic subject / 多文件）
///     是弱信号 —— 多条叠加才升级
///   - **纯函数**：无副作用，方便测试
enum AICommitDetector {

    /// 启发式判断单个 commit。
    /// - Parameters:
    ///   - author: commit author 字符串
    ///   - authorEmail: %ae 拿到的 email（更可靠）
    ///   - subject: commit message 第一行
    ///   - trailers: commit body 末尾的 trailer 段（`%(trailers:only=true,unfold=true)`）
    ///     —— Claude Code 用 `Co-Authored-By: Claude … <noreply@anthropic.com>` 写在这里
    ///   - changedFileCount: 这个 commit 改了几个文件（0 = 跳过这个信号）
    static func detect(
        author: String,
        authorEmail: String?,
        subject: String,
        trailers: String? = nil,
        changedFileCount: Int = 0
    ) -> AILikelihood {
        var score = 0

        let emailLower = (authorEmail ?? "").lowercased()
        let authorLower = author.lowercased()
        let subjectLower = subject.lowercased()
        let trailersLower = (trailers ?? "").lowercased()

        // === 强信号 (2 pts each) — 单条就足以 likelyAI ===

        // 强信号 A: author 本身就是已知 AI 工具的 service account
        // 比泛 "[bot]" 更精确：只匹配 Claude/Cursor 等真生成式 AI tools
        let strongAIAuthorPatterns = [
            "noreply@anthropic.com",
            "claude@anthropic.com",
            "cursor@cursor",
            "noreply@cursor.so",
        ]
        if strongAIAuthorPatterns.contains(where: emailLower.contains) ||
           strongAIAuthorPatterns.contains(where: authorLower.contains) {
            score += 2
        }

        // 强信号 B: subject OR trailer 里有 explicit AI 协作 attribution
        // Claude Code 最常见做法：trailer 里 `Co-Authored-By: Claude … <noreply@anthropic.com>`
        let aiAttributionMarkers = [
            "co-authored-by: claude",
            "co-authored-by: cursor",
            "co-authored-by: github copilot",
            "co-authored-by: codex",
            "co-authored-by: aider",
            "🤖 generated with [claude code]",   // Claude Code 的标准签名格式
            "noreply@anthropic.com",              // trailer 里的 Claude email
            "noreply@cursor.so",                  // trailer 里的 Cursor email
        ]
        let foundAttribution = aiAttributionMarkers.contains(where: {
            subjectLower.contains($0) || trailersLower.contains($0)
        })
        if foundAttribution {
            score += 2
        }

        // === 弱信号 (1 pt each) — 需要叠加才升级 ===

        // 弱信号 C: 泛 bot pattern（可能是 dependabot/renovate 这种确定性 bot，未必 AI）
        // 强信号 A 已命中时跳过，避免重复计分
        let foundStrongAuthor = strongAIAuthorPatterns.contains(where: emailLower.contains) ||
                                strongAIAuthorPatterns.contains(where: authorLower.contains)
        if !foundStrongAuthor {
            let weakBotPatterns = ["agent@", "@bot.", "[bot]"]
            if weakBotPatterns.contains(where: emailLower.contains) ||
               weakBotPatterns.contains(where: authorLower.contains) {
                score += 1
            }
        }

        // 弱信号 D: subject 含"generated by" 等较弱的标记
        let aiSubjectHints = [
            "generated with claude",
            "generated by cursor",
            "🤖 generated",
        ]
        if !foundAttribution && aiSubjectHints.contains(where: subjectLower.contains) {
            score += 1
        }

        // 弱信号 E: 一次改 ≥15 文件（人类 commit 通常 ≤5；AI 经常大片 refactor）
        if changedFileCount >= 15 {
            score += 1
        }

        // 弱信号 F: subject 是 generic 占位词
        let trimmedSubject = subjectLower.trimmingCharacters(in: .whitespacesAndNewlines)
        let genericSubjects: Set<String> = [
            "updated files", "fix bug", "fix bugs", "update code",
            "update", "updates", "wip", "stuff", "changes", "misc", "fixes",
        ]
        if genericSubjects.contains(trimmedSubject) {
            score += 1
        }

        switch score {
        case 0:  return .unknown
        case 1:  return .maybeAI
        default: return .likelyAI
        }
    }
}
