import XCTest
@testable import Pilo

/// S1 AI Push Guard：AICommitDetector 启发式测试。
///
/// 信号权重：
///   - 强 (2pts)：author 是已知 AI tool service account / subject∪trailer 含明确
///     `Co-Authored-By: <AI tool>` 或已知 AI email —— 单条就 likelyAI
///   - 弱 (1pt)：泛 [bot] 后缀 / generic subject / 改 ≥15 文件 / "generated by" 软提示
///
/// 阈值：0 = unknown / 1 = maybeAI / ≥2 = likelyAI
final class AICommitDetectorTests: XCTestCase {

    // MARK: - 强信号单条 → likelyAI

    func testNoreplyAuthorEmailIsLikelyAI() {
        // author 本身就是 Claude service account —— 不需要其他信号
        let r = AICommitDetector.detect(
            author: "Claude",
            authorEmail: "noreply@anthropic.com",
            subject: "fix typo",
            changedFileCount: 1
        )
        XCTAssertEqual(r, .likelyAI, "AI tool service account 作 author 必然 likelyAI")
    }

    func testCursorServiceAccountIsLikelyAI() {
        let r = AICommitDetector.detect(
            author: "Cursor",
            authorEmail: "noreply@cursor.so",
            subject: "Refactor",
            changedFileCount: 3
        )
        XCTAssertEqual(r, .likelyAI)
    }

    // MARK: - Trailer 信号（新加，修旧 bug）

    func testTrailerCoAuthoredByClaudeIsLikelyAI() {
        // 关键 case：Pilo 自己的 commit 就长这样
        // author = Emma；body trailer = "Co-Authored-By: Claude … <noreply@anthropic.com>"
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "feat: add new flow",
            trailers: "Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>",
            changedFileCount: 3
        )
        XCTAssertEqual(r, .likelyAI, "trailer 里有 Claude 明确 attribution → likelyAI")
    }

    func testTrailerWithAnthropicEmailIsLikelyAI() {
        // trailer 里只有 email 没有 "Co-Authored-By" 关键字也应该被捕获
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "ship feature",
            trailers: "Generated alongside <noreply@anthropic.com>",
            changedFileCount: 2
        )
        XCTAssertEqual(r, .likelyAI)
    }

    func testTrailerCoAuthoredByCursor() {
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "feat: x",
            trailers: "Co-Authored-By: Cursor",
            changedFileCount: 2
        )
        XCTAssertEqual(r, .likelyAI)
    }

    func testTrailerCoAuthoredByCodex() {
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "feat: x",
            trailers: "Co-Authored-By: Codex CLI <noreply@openai.com>",
            changedFileCount: 2
        )
        XCTAssertEqual(r, .likelyAI)
    }

    func testTrailerCoAuthoredByAider() {
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "refactor: x",
            trailers: "Co-Authored-By: Aider",
            changedFileCount: 2
        )
        XCTAssertEqual(r, .likelyAI)
    }

    func testTrailerCoAuthoredByCopilot() {
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "wip: x",
            trailers: "Co-Authored-By: GitHub Copilot",
            changedFileCount: 2
        )
        XCTAssertEqual(r, .likelyAI)
    }

    func testNilTrailerStillWorks() {
        // 不传 trailer 时不该崩
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "fix race condition properly",
            trailers: nil,
            changedFileCount: 3
        )
        XCTAssertEqual(r, .unknown)
    }

    func testEmptyTrailerStillWorks() {
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "fix race condition properly",
            trailers: "",
            changedFileCount: 3
        )
        XCTAssertEqual(r, .unknown)
    }

    // MARK: - subject 里直接含 Co-Authored-By（兼容老格式）

    func testSubjectWithCoAuthoredByClaudeIsLikelyAI() {
        // 旧代码 / 旧测试场景：commit message 整段塞到 subject
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@x.com",
            subject: "Add reminder flow\n\nCo-Authored-By: Claude",
            trailers: nil,
            changedFileCount: 4
        )
        XCTAssertEqual(r, .likelyAI, "subject 里也得识别（向后兼容）")
    }

    // MARK: - 弱信号单条 → maybeAI

    func testGenericSubjectMaybeAI() {
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@personal.com",
            subject: "WIP",
            changedFileCount: 3
        )
        XCTAssertEqual(r, .maybeAI, "generic subject 单弱信号 → maybeAI")
    }

    func testManyFilesMaybeAI() {
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@personal.com",
            subject: "refactor auth module",
            changedFileCount: 20
        )
        XCTAssertEqual(r, .maybeAI, "改 ≥15 文件单弱信号 → maybeAI")
    }

    func testBotEmailMaybeAI() {
        // dependabot 等"自动化但不一定是 AI"的 bot —— 弱信号
        let r = AICommitDetector.detect(
            author: "dependabot[bot]",
            authorEmail: "49699333+dependabot[bot]@users.noreply.github.com",
            subject: "Bump foo from 1.0 to 1.1",
            changedFileCount: 2
        )
        XCTAssertEqual(r, .maybeAI, "[bot] 后缀是弱信号（不一定是生成式 AI）")
    }

    // MARK: - 多弱信号叠加 → likelyAI

    func testGenericPlusManyFilesLikelyAI() {
        // 两个弱信号也升级
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "updated files",
            changedFileCount: 25
        )
        XCTAssertEqual(r, .likelyAI, "两个弱信号叠加 → likelyAI")
    }

    func testBotPlusGenericLikelyAI() {
        let r = AICommitDetector.detect(
            author: "renovate[bot]",
            authorEmail: "renovate[bot]@users.noreply.github.com",
            subject: "update",
            changedFileCount: 3
        )
        XCTAssertEqual(r, .likelyAI)
    }

    // MARK: - 零信号 → unknown

    func testHumanCommitIsUnknown() {
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "fix race condition in token refresh",
            changedFileCount: 3
        )
        XCTAssertEqual(r, .unknown, "正常人类 commit 应保持 unknown")
    }

    func testRefactorBy人类NotFlagged() {
        // 14 文件刚好低于阈值 + specific subject
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: "emma@gmail.com",
            subject: "Migrate from old auth API to new session-based flow",
            changedFileCount: 14
        )
        XCTAssertEqual(r, .unknown)
    }

    func testEmptySubjectIsUnknownNotCrash() {
        let r = AICommitDetector.detect(
            author: "Emma",
            authorEmail: nil,
            subject: "",
            changedFileCount: 0
        )
        XCTAssertEqual(r, .unknown)
    }

    // MARK: - 边界

    func testFileCountBoundary() {
        XCTAssertEqual(
            AICommitDetector.detect(author: "x", authorEmail: nil, subject: "specific subject here", changedFileCount: 14),
            .unknown
        )
        XCTAssertEqual(
            AICommitDetector.detect(author: "x", authorEmail: nil, subject: "specific subject here", changedFileCount: 15),
            .maybeAI
        )
    }

    // MARK: - Regression guard

    func testStrongAuthorDoesNotDoubleCountBotSignal() {
        // author = noreply@anthropic.com 命中强信号 A；同时 email 里也有 "noreply" 这种
        // bot-ish 子串—— 不该额外再算弱信号 C
        let r = AICommitDetector.detect(
            author: "noreply",
            authorEmail: "noreply@anthropic.com",
            subject: "specific subject",
            changedFileCount: 3
        )
        XCTAssertEqual(r, .likelyAI, "强信号 +2 = 2 → likelyAI；不该被错算成 3")
    }
}
